# Generated by Django 3.0.4 on 2020-03-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200326_1947'),
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.Employee'),
        ),
    ]
