# Generated by Django 3.0.4 on 2020-03-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20200326_1948'),
        ('documents', '0002_document_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.Employee'),
        ),
    ]
